name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t username/repository-name:latest .

      # 4. Publicar la imagen en Docker Hub
      - name: Push Docker image
        run: |
          docker push username/repository-name:latest
